### ISSUE TITLE
Docs, please

### ISSUE THREAD

**Issue by blalor** [cavaliercoder/y10k#1]
This looks really handy, and I've poked through the source to figure out what it's doing, but I think a little back-story would be useful to help folks figure out why they'd want to use it.

**Comment by cavaliercoder** [comment]
I didn't anticipate any attention on this project yet... but thanks for your interest! I will work to improve the documentation ASAP.

I've added some context to the README in the meantime.

**Comment by blalor** [comment]
Ha!  You can thank devops weekly for that! :-)

**Comment by cavaliercoder** [comment]
Do you happen to have a URL? I couldn't find anything. Is the http://www.devopsweekly.com/ mailing list?

**Comment by blalor** [comment]
@garethr looks like the [archive](http://www.devopsweekly.com/archive) is out of date. :-)

> DEVOPS WEEKLY
> ISSUE #240 - 9th August 2015
> 
> Results from one survey (The Monitoring Survey 2015) and a request to complete another one (Ethical Obligations in Internet Operations) this week. It’s great that individuals in our community help to collect, curate and analyse data that can help all of us improve. Good job everyone involved.
> 
> # Sponsor
> 
> Devops Weekly is sponsored by Brightbox Cloud: the multi-zone cloud platform built for High Availability.
> 
> Try an SSD cloud server in 30 seconds with your £20 free credit…
> 
> http://brightbox.com/devopsweekly
> 
> # Sponsored
> 
> [Webinar] How to Use DevOps & APM to Release Better Software Faster
> 
> Join us for a talk with Hasan Yasar, Technical Manager of Carnegie Mellon's Software Engineering Institute, to learn the benefits of DevOps, automation and CD, where APM fits in DevOps, and why you need to monitor. Finally, find out all about auto-provisioning and deployment with Docker, Vagrant, Ansible, and more. Register now.
> 
> http://ow.ly/Q3waZ
> 
> # News
> 
> Results from the 2015 monitoring survey are starting to be published, with lots of data and analysis of the current state of tooling and what people are monitoring with them.
> 
> http://kartar.net/2015/08/monitoring-survey-2015---background/
> http://kartar.net/2015/08/monitoring-survey-2015---demographics/
> http://kartar.net/2015/08/monitoring-survey-2015---tools/
> http://kartar.net/2015/08/monitoring-survey-2015---environments/
> 
> A fun presentation I gave this week at the London Web Performance meetup, trying to combat the hype surrounding containers and microservices with some critical thinking around performance.
> 
> https://speakerdeck.com/garethr/containers-and-microservices-make-performance-worse
> 
> Makefiles are awesome, I’ve lost count of the the number of times I’d rather be using Make than a programming-language-specific derivative. This site has a nice set of tutorials for understanding the basics.
> 
> http://makefiletutorial.com/
> 
> Learning from failure, and being open about operational issues, has definitely been one of the properties of the devops community I like the most. This detailed downtime postmortem has lots of great details to learn from.
> 
> http://community.eveonline.com/news/dev-blogs/behind-the-scenes-of-a-long-eve-online-downtime
> 
> An interesting questionnaire on the ethical obligations in internet operations, collecting information ahead of a talk for Velocity NYC. I’d love to see people fill this out and look forward to featuring the results in October.
> 
> https://docs.google.com/forms/d/1UmJtkj1dsFVjZx2yBC6zZZi1tIuObuVZxQd3oWxGk4o/viewform
> 
> Puppet 4 (obligatory disclaimer that I work for Puppet Labs) has been around a little while now and this blog post delves into some of the new features and functionality.
> 
> https://www.devco.net/archives/2015/07/31/shiny-new-things-in-puppet-4.php
> 
> Some good tips for anyone moving to more of a service based architecture having previously used the database for integrating applications.
> 
> http://blog.skeltonthatcher.com/2015/08/06/database-connection-auditing-for-continuous-delivery/
> 
> It’s easy to measure AWS purely on all the new features being shipping but the internal improvements are also impressive. This post features benchmarking of AWS network connectivity, showing a 40% improvement in some areas on the same tests a year ago.
> 
> http://blog.takipi.com/amazon-ec2-2015-benchmark-testing-speeds-between-aws-ec2-and-s3-regions/
> 
> # Jobs
> 
> Want to work on new projects? Try a new stack? Join Hired and discover new opportunities today.
> 
> http://hrd.cm/1Ghn0BB
> 
> # Events
> 
> Iterate.PHX is a new Devops conference in Phoenix on the 1st of September. Tickets are already available, and the organisers are looking for more sponsors and speakers for the event.
> 
> http://www.iteratephx.co/
> 
> Devopsdays Warsaw is coming up on the 24th and 25th of November. The call for proposals just opened and is open until the 30th of September and the organisers are on the lookout for sponsors too.
> 
> http://devopsdays.pl/
> http://www.devopsdays.org/events/2015-warsaw/
> 
> Another upcoming Devopsdays event, this time in Charlotte on November 2nd and 3rd. The usual mix of talks, ignites and open spaces are planning. The organisers are looking for sponsors and potential speakers.
> 
> http://www.devopsdays.org/events/2015-charlotte/
> 
> # Tools
> 
> Y10K is a tool to deploy Yum/RPM repositories and mirrors in your local environment using settings described in a simple Yumfile.
> 
> https://github.com/cavaliercoder/y10k
> 
> Terraframe is an interesting approach to using Terraform for describing your infrastructure, specifically it provides Ruby based DSL interface rather than HCL.
> 
> https://github.com/eropple/terraframe
> 
> An interesting approach to building an application using the latest AWS features. Specifically it combines Lambda, API Gateway and DynamoDB for a stack that requires no managed servers.
> 
> https://github.com/jaws-stack/JAWS
> 
> Devops Weekly is sponsored by Brightbox Cloud: the multi-zone cloud platform built for High Availability.
> 
> Try an SSD cloud server in 30 seconds with your £20 free credit…
> http://brightbox.com/devopsweekly
> 
> If you received this email directly then you're already signed up, thanks! If however someone forwarded this email to you and you'd like to get it each week then you can subscribe at http://devopsweekly.com
> 
> ## 
> 
> You opted in for Devops Weekly at http://devopsweekly.com
> 
> You can always unsubscribe by visiting …
> 
> If you have other queries you can contact the list maintainer at @garethr
> 
> Our mailing address is 43 Gwydir Street, Cambridge, UK, CB1 2LG

**Comment by cavaliercoder** [comment]
I've added a few pages in GitHub Pages. Hopefully it covers everything so far. I'll expand on it as new features are developed.

http://cavaliercoder.github.io/y10k/

**Comment by blalor** [comment]
👍
